{
 "title": "PVP-Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "连接数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "microsoft_aspnetcore_server_kestrel_current_connections{job=\"bq-yakyu-pvp-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "接收流量(KiB/S)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(system_net_sockets_bytes_received{job=\"bq-yakyu-pvp-metrics\"}[$__interval]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "发送流量(KiB/S)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(system_net_sockets_bytes_sent{job=\"bq-yakyu-pvp-metrics\"}[$__interval]) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存(GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "process_private_memory_bytes{job=\"bq-yakyu-pvp-metrics\"}/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 22, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"bq-yakyu-pvp-metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}